### ISSUE TITLE
ACEMD expired license error running TTMD

### ISSUE THREAD

**Issue by mglgc** [molecularmodelingsection/TTMD#10]
Hi,
Running TTMD jobs unsuccessfully end with an error message about ACEMD expired license:
  Licence:
  #   Check floating licence:
  #     ACELLERA_LICENCE_SERVER -- not defined
  #     ACELLERA_LICENSE_SERVER -- not defined
  #   Check node-locked licence:
  #     ACELLERA_LICENCE_FILE -- not defined
  #     ACELLERA_LICENSE_FILE -- not defined
  #     /opt/acellera/licence.dat -- DENIED (Unable to locate target file)
  #     /opt/acellera/license.dat -- DENIED (Unable to locate target file)
  #     /home/csic/sdb/mgl/.acellera/licence.dat -- DENIED (Unable to locate
  target file)
  #     /home/csic/sdb/mgl/.acellera/license.dat -- DENIED (Unable to locate
  target file)
  #
  # This version of ACEMD has expired!
  # You should update to the latest version.
  # If you want to continue using this version, you need a licence.

Please, could you update the TTMD conda environment to fix that license issue? Thank you very much in advance for your reply.

**Comment by molecularmodelingsection** [comment]
Hi Mario!
Since we are currently working on an updated TTMD repack version, we are not currently updating the main TTMD branch.
Fortunately, we have already met this error using acemd v3.5.0, which can be solved by updating to v3.5.1.
Please check your conda env to see which acemd version is installed.
You can rebuild the whole env from our file ttmd.txt (with acemd v3.5.1, it's in the main branch) by running the following command:
`conda create -n <env> --file <ttmd.txt>`

Let me know if it works!
SM

**Comment by mglgc** [comment]
Hi,
Thank you for your promptly reply. We have just rebuilt the whole ttmd env from your ttmd.txt file but unfortunately the license issue remains. The acemd version installed is 3.5.1. Any other action to take into account to fix it?
Thanks a lot in advance for your reply.

> Hi Mario! Since we are currently working on an updated TTMD repack version, we are not currently updating the main TTMD branch. Fortunately, we have already met this error using acemd v3.5.0, which can be solved by updating to v3.5.1. Please check your conda env to see which acemd version is installed. You can rebuild the whole env from our file ttmd.txt (with acemd v3.5.1, it's in the main branch) by running the following command: `conda create -n <env> --file <ttmd.txt>`
> 
> Let me know if it works! SM

**Comment by molecularmodelingsection** [comment]
Hi Mario,
I hope you are doing well.
I'm sorry for the late reply.
While trying to solve your issue, I rebuilt the entire conda env with the latest acemd3 version (3.7.2), which you can find attached and ready to clone.
[latest.txt](https://github.com/molecularmodelingsection/TTMD/files/13297724/latest.txt)

In this way, you should be able to run the simulations.
Unfortunately, there are some compatibility issues with the code, indeed you will need to use the old conda env only for generate final graphs.

Let me know if this solution finally works.
Thank you for your patience and your trust on our software.

Regards,
SM

**Comment by mglgc** [comment]
Hi SM,
Thank you very much for your reply. I'll let you know the result. Meanwhile, please could you elaborate a bit more how to generate the final graphs from results coming from a previous TTMD run?
Regards.

> Hi Mario, I hope you are doing well. I'm sorry for the late reply. While trying to solve your issue, I rebuilt the entire conda env with the latest acemd3 version (3.7.2), which you can find attached and ready to clone. [latest.txt](https://github.com/molecularmodelingsection/TTMD/files/13297724/latest.txt)
> 
> In this way, you should be able to run the simulations. Unfortunately, there are some compatibility issues with the code, indeed you will need to use the old conda env only for generate final graphs.
> 
> Let me know if this solution finally works. Thank you for your patience and your trust on our software.
> 
> Regards, SM

**Comment by molecularmodelingsection** [comment]
Hi Mario,
to produce simulation files, you just need to activate the conda env updated version and run TTMD.
At this point, the software will raise error when generating graphs. Then you can simply activate the older env and run the software in the same folder, just to generate the final graphs.

In fact, by running TTMD, the software initially checks if there is any missing file and, if that's the case, those files are generated.
So, in your case, if you run TTMD-old env in the folder with the completed simulations, the software will simply resume and generate the graphs.

Please, feel free to contact me if you have any other question.

Kind regards,
Silvia

**Comment by mglgc** [comment]
Hi Silvia,
Thanks a lot for your promptly reply. The fix running the old ttmd conda env after the latest one has finished works. Please, we'd be glad if you let us know when the TTMD software remains finally fixed.
Kind regards.


> Hi Mario, to produce simulation files, you just need to activate the conda env updated version and run TTMD. At this point, the software will raise error when generating graphs. Then you can simply activate the older env and run the software in the same folder, just to generate the final graphs.
> 
> In fact, by running TTMD, the software initially checks if there is any missing file and, if that's the case, those files are generated. So, in your case, if you run TTMD-old env in the folder with the completed simulations, the software will simply resume and generate the graphs.
> 
> Please, feel free to contact me if you have any other question.
> 
> Kind regards, Silvia

**Comment by saranthee** [comment]
ear Molecularmodelingsection/Ttmd,

I have taken into account your feedback, however, I continue to encounter the "**check device setting**" error consistently.
I have utilized the test protein and ligand files, along with the config_rt.dat files provided by you.
My system setup consists of a DELL Precision 3660 with an NVIDA RTX A2000 12GB GPU and 64GB of RAM. Would this configuration be suitable for conducting TTMD calculations?
I would greatly appreciate your assistance in resolving this matter.
