### ISSUE TITLE
TTMD Test Case Execution Error During 'equil1' Stage

### ISSUE THREAD

**Issue by surendramph** [molecularmodelingsection/TTMD#11]
Dear Sir,
I have been attempting to replicate the TTMD job using the test case supplied within the repository.
Following the installation of the required packages, I was able to initiate the job successfully.
Unfortunately, I encountered an error during the 'equil1' stage, causing the job to terminate prematurely. I have attached the terminal output in a .txt file here for your examination and troubleshooting guidance.
Any assistance you can provide to resolve this issue would be greatly appreciated.

Thank you for your time and support.

Best regards,
Surendra

[error.txt](https://github.com/molecularmodelingsection/TTMD/files/13261010/error.txt)

**Comment by molecularmodelingsection** [comment]
Dear Surendra,
thank you for your interest in our TTMD software.
To solve your issue, I would kindly ask you to try a couple of tests to verify that your system is set up correctly:

1. If you already had experience with acemd, please try to run one of your configuration files and see if it works
2. Try to run the ttmd generated equil1.nvt file from command line `acemd3 equil1.nvt --device 0`
3. In addition, could you please provide us the conda env you are using? Please export it with the command `conda list --explicit > env.txt`
Best regards,
SM

**Comment by surendramph** [comment]
Dear Sir,

Thank you for your prompt response.

I am attaching my ttmd_env.txt (conda file) file for your reference.

Upon executing the command **acemd3 equil1.nvt --device 0**, the process terminated with an error. 
Please find the attached file detailing the error message encountered.

The critical error reported was:

**"ACEMD failed:
    Error executing FFT: 6"**

[equil1.error.txt](https://github.com/molecularmodelingsection/TTMD/files/13275170/equil1.error.txt)
[ttmd_env.txt](https://github.com/molecularmodelingsection/TTMD/files/13275171/ttmd_env.txt)

I appreciate your time and support in resolving this issue.

Best regards,
Surendra

**Comment by molecularmodelingsection** [comment]
Dear Surendra,
I suspect that the error is caused by the acemd3 software.
To investigate this hypothesis, I would kindly ask you to accomplish the [acemd tutorial](https://software.acellera.com/acemd/tutorial.html#molecular-dynamics-simulation-of-dhfr) to see if the system crash or not.
You could also try it changing the acemd version, using, for example, v3.7.2 and v3.5.1.
This will help us understanding if the problem is due to the TTMD software or the acemd3 package or the version you are using.

I'm looking forward to hearing from you soon.

Kind regards,
Silvia

**Comment by surendramph** [comment]
Dear Sir,

Apologies for my delayed reply. 
Upon downgrading ACEMD from version 3.7.1 to 3.5.1, I encountered a message indicating that the license has expired.

**acemd3 equil1.nvt --device 0**

## ACEMD version 3.5.1

## Copyright (C) 2017-2022 Acellera ([www.acellera.com](http://www.acellera.com/))

## When publishing, please cite:
##   ACEMD: Accelerating Biomolecular Dynamics in the Microsecond Time Scale
##  M. J. Harvey, G. Giupponi and G. De Fabritiis,
##   J Chem. Theory. Comput. 2009 5(6), pp1632-1639
##   DOI: 10.1021/ct9000685

## Arguments:
##   input: input
##   platform: 
##   device: 
##   ncpus: 
##   precision: mixed

## Licence:
##   Check floating licence:
##     ACELLERA_LICENCE_SERVER -- not defined
##     ACELLERA_LICENSE_SERVER -- not defined
##   Check node-locked licence:
##     ACELLERA_LICENCE_FILE -- not defined
##     ACELLERA_LICENSE_FILE -- not defined
##     /opt/acellera/licence.dat -- DENIED (Unable to locate target file)
##     /opt/acellera/license.dat -- DENIED (Unable to locate target file)
##     /home/medicina/.acellera/licence.dat -- DENIED (Unable to locate target file)
##     /home/medicina/.acellera/license.dat -- DENIED (Unable to locate target file)

## This version of ACEMD has expired!
## You should update to the latest version.
## If you want to continue using this version, you need a licence.


After installing the TTMD package on another computer with ACEMD version 3.7.1, I successfully executed a TTMD job using a test file. This leads me to believe that the problem isn't with TTMD, but rather with the first machine where ACEMD is experiencing difficulties. I'm unsure why the TTMD job failed on one machine but worked on another. It's possible that the machine with issues is missing some necessary libraries or has a configuration problem that's hindering ACEMD's proper execution.

After executing the job, I obtained various files including **'titration_profile'** and **'titration_timeline'**. I noticed in your publication the mention of figures pertaining to **per-residue interaction energy**, which were not included in this TTMD package. Should I generate these plots separately? If so, could you advise on which software or package would be suitable for creating such plots?

I'd like to express my appreciation for the excellent package you've provided.

Kind Regards,

Surendra

**Comment by molecularmodelingsection** [comment]
Dear Surendra,
I'm happy to know that the problem origin has been identified.

Currently, the per-residue IE is limited to the "protein stability" protocol. You can find it in the experimental branch, using 'ps' as method. Unfortunately, this was developed to study per-residue interactions between two proteins or subunits, indeed not for protein-ligand interactions, but you can try to modify the code to make it suitable for such interactions.

Thank you for your appreciation for our TTMD software.

Kind regards,
Silvia
