### ISSUE TITLE
charge file required for the ligand

### ISSUE THREAD

**Issue by mglgc** [molecularmodelingsection/TTMD#6]
Hi,
Additionally to the pdb and mol2 files for protein and ligand, respectively, the TTMD python code asks for one more file for the ligand charges, a requirement not explained in any docu. Please, could the TTMD developers shed some light on the proper format for such a charge file?
Thank you very much in advance for the reply.

**Comment by molecularmodelingsection** [comment]
Hi,
thank you for showing interest in using our code.
To specify the ligand charge you don't need to use any file. You only need to write down in an integer the charge, for example, 0 or +1 or -1, and so on.
At the moment, we are working on implementing an automatic ligand charge calculator in the next release.
